
[build]
command = "npm run build"
publish = "dist"

[[headers]]
for = "/*"
[headers.values]
Content-Type = "text/javascript; charset=UTF-8"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
